{% set name = "pathlib-mate" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pathlib_mate-{{ version }}.tar.gz
  sha256: 8241c3ca06bc007e2cc3f33d275d59ec2da2cd66af911abf46b5d0cbcbb1e918

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - atomicwrites
    - autopep8
    #- scandir  # [py<35]
    - six

test:
  imports:
    - pathlib_mate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MacHu-GWU/pathlib_mate-project
  summary: An extended and more powerful pathlib.
  license: MIT
  license_file: LICENSE.txt
  description: |
    `pathlib` is an awesome library handling path in different OS. And it’s 
    been added into standard library since Python3.4. pathlib_mate gives 
    extensive methods and attributes, makes pathlib more powerful and 
    user-friendly.

    PyPI: [https://pypi.org/project/pathlib-mate/](https://pypi.org/project/pathlib-mate/)

  doc_url: https://pathlib_mate.readthedocs.io/index.html
  dev_url: https://github.com/MacHu-GWU/pathlib_mate-project
extra:
  recipe-maintainers:
    - sugatoray
